# Generated by Django 3.1.4 on 2020-12-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=20)),
                ('objective', models.CharField(default='', max_length=200)),
                ('type', models.CharField(default='', max_length=200)),
                ('organization_name', models.CharField(max_length=200)),
                ('organization_picture', models.URLField(default='')),
                ('locations', models.CharField(default='', max_length=200)),
                ('remote', models.BooleanField(default=False)),
                ('skills', models.CharField(default='', max_length=200)),
                ('compensation', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Search',
        ),
    ]
