# Generated by Django 3.1.4 on 2020-12-17 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_skill_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
